hw terraform
Otus-DevOps-2021-08/fjorny_infra pull request #5
Opened 2021-12-12 13:36 UTC by fjorny

# Выполнено ДЗ №

 - [ ] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
 - Пункт 1
 - Пункт 2

## Как запустить проект:
 - Например, запустить команду X в директории Y

## Как проверить работоспособность:
 - Например, перейти по ссылке http://localhost:8080

## PR checklist
 - [ ] Выставил label с номером домашнего задания
 - [ ] Выставил label с темой домашнего задания

2021-12-12 14:54 UTC, mrgreyves requested changes
Здравствуйте!)
Проверил ваше дз.
Оставил комментарий к файлу, так же вам стоит обратить внимание на результаты тестов 
ДЗ возвращаю на доработку =)

2021-12-12 14:54 UTC, mrgreyves commented on terraform/variables.tf
> +variable "image_id" {
Вот тут нужно поправить =)

2021-12-12 19:37 UTC, fjorny commented on terraform/variables.tf
> +variable "image_id" {
Тесты пройдены

2021-12-13 20:21 UTC, mrgreyves approved these changes
Здравствуйте!)
Вот теперь апрув =)

2021-12-14 06:28 UTC, merged