test
Otus-DevOps-2021-08/fjorny_infra pull request #6
Opened 2022-01-11 20:04 UTC by fjorny

# Выполнено ДЗ terraform 2

2022-01-11 21:43 UTC, fjorny commented
Перепишу завтра

2022-01-12 09:48 UTC, mrgreyves requested changes
Здравствуйте!)
Проверил ваше дз
Рекомендую проверить результаты тестов, что-то там слишком много красного 0_о
Исходя из ошибок, там не страшно
Правки не займут много времени =)

2022-01-17 11:19 UTC, fjorny commented
Ну, вроде, готово :)

2022-01-19 14:55 UTC, mrgreyves approved these changes
Здравствуйте!)
Вот теперь точно апрув =)

2022-01-19 14:56 UTC, merged